# Generated by Django 4.0.5 on 2022-06-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiarapi', '0002_alter_persona_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='documento',
            field=models.IntegerField(unique=True),
        ),
    ]
